<?php $this->headTitle('ShowCase Offer\'s');?>

<?php //var_dump($pagi); ?>

<table class="table">
    <thead>
    <tr>
        <th>id</th>
        <th>name</th>
        <th>description</th>
        <th>price</th>
        <th>picture</th>
        <th>categoreId</th>
        <th>modified_datetime</th>
        <th>currencyId</th>
        <th>brand_name</th>
    </tr>
    </thead>
    <tbody>
        <?php foreach ($this->pagi as $a): ?>
            <tr>
                <td><?php echo $a->id; ?></td>
                <td><?php echo $a->name; ?></td>
                <td><?php echo $a->description; ?></td>
                <td><?php echo $a->price; ?></td>
                <td><?php echo $a->picture; ?></td>
                <td><?php echo $a->categoryId; ?></td>
                <td><?php echo $a->modified_datetime; ?></td>
                <td><?php echo $a->currencyId; ?></td>
                <td><?php echo $a->brand_name; ?></td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>

<?php    echo $this->paginationControl(
    $this->pagi,
    'sliding',
    'application/partials/paginator.phtml'
);?>
