<?php $this->headTitle('ShowCase Offer');

var_dump($offer); ?>

<!--<table class="table">-->
<!--    <thead>-->
<!--    <tr>-->
<!--        <th>id</th>-->
<!--        <th>name</th>-->
<!--        <th>description</th>-->
<!--        <th>price</th>-->
<!--        <th>picture</th>-->
<!--        <th>categoreId</th>-->
<!--        <th>modified_datetime</th>-->
<!--        <th>currencyId</th>-->
<!--        <th>brand_name</th>-->
<!--    </tr>-->
<!--    </thead>-->
<!--    <tbody>-->
<!--        <tr>-->
<!--            <td>--><?php //echo $offer->id; ?><!--</td>-->
<!--            <td>--><?php //echo $offer->name; ?><!--</td>-->
<!--            <td>--><?php //echo $offer->description; ?><!--</td>-->
<!--            <td>--><?php //echo $offer->price; ?><!--</td>-->
<!--            <td>--><?php //echo $offer->picture; ?><!--</td>-->
<!--            <td>--><?php //echo $offer->categoreId; ?><!--</td>-->
<!--            <td>--><?php //echo $offer->modified_datetime; ?><!--</td>-->
<!--            <td>--><?php //echo $offer->currencyId; ?><!--</td>-->
<!--            <td>--><?php //echo $offer->brand_name; ?><!--</td>-->
<!--        </tr>-->
<!--    </tbody>-->
<!--</table>-->
